-- Create the cs_items table
CREATE TABLE IF NOT EXISTS public.cs_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  def_index integer NOT NULL,
  def_name text NOT NULL,
  paint_index integer,
  paint_name text,
  max_float numeric,
  min_float numeric,
  category integer NOT NULL DEFAULT 0,
  market_hash_name text,
  image_url text,
  created_at timestamp with time zone DEFAULT now()
);

-- Add table comment
COMMENT ON TABLE public.cs_items IS 'Table storing CS2 items with their properties';

-- Set up Row Level Security (RLS)
ALTER TABLE public.cs_items ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access on cs_items"
  ON public.cs_items
  FOR SELECT
  USING (true);

-- Create policy for authenticated users to insert items
CREATE POLICY "Allow authenticated insert on cs_items"
  ON public.cs_items
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Create policy for authenticated users to update their own items
CREATE POLICY "Allow authenticated update on cs_items"
  ON public.cs_items
  FOR UPDATE
  USING (auth.role() = 'authenticated'); 